---

- name: RedHat
  include_tasks: redhat.yml
  when: ansible_facts['os_family']|lower == 'redhat'

- name: Ubuntu and debian
  include_tasks: ubuntu.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Windows Server and Workstation
  include_tasks: windows.yml
  when: ansible_facts['os_family']|lower == 'windows'