---
- name: Checking for BigFix agent installed
  stat:
    path: /etc/init.d/besclient
  register: agent

- debug:
    msg: "{{ 'Bigfix agent is found' if agent.stat.exists else 'Bigfix agent is not found' }}"
 
- name: Create necessary folders
  file:
    path: "{{ item }}"
    recurse: yes
    state: directory
    mode: 0500
  loop:
  - "{{ linux_agent_install_path }}"
  - "{{ linux_agent_config_path }}"
  - "/build-artifacts/"
  when: not agent.stat.exists
  
- name: Copy besclient.config to config folder
  copy:
    src: besclient.config
    dest: "{{ linux_agent_config_path }}/besclient.config"
  when: not agent.stat.exists

- name: Update besclient.config for Bigfix custom properties
  lineinfile:
    path: "{{ linux_agent_config_path }}/besclient.config"
    create: yes
    backup: yes
    insertafter: EOF
    mode: 0644
    line: |
      [Software\BigFix\EnterpriseClient\Settings\Client\{{ item.name }}]
      value                          = {{ item.value }}
      effective date                 = Tue,%2003%20Nov%202020%2009:32:11%20-0500
      
  with_items:
    - "{{ bigfix_custom_properties }}"
  when: not agent.stat.exists

- name: Copy installer files to remote server
  copy:
    src: "{{ role_path }}/files/{{ BIGFIX_AGENT_PACKAGE_NAME }}"
    dest: "/build-artifacts/{{ BIGFIX_AGENT_PACKAGE_NAME }}"

- name: Install Bigfix agent
  apt:
    deb: /build-artifacts/{{ BIGFIX_AGENT_PACKAGE_NAME  }}
  when: not agent.stat.exists
  
- name: Copy actionsite.afxm to install folder
  copy:
    src: "actionsite.afxm"
    dest: "{{ linux_agent_install_path }}/actionsite.afxm"
  when: not agent.stat.exists

- name: Verify Bigfix service started
  service:
    name: besclient
    enabled: yes
    state: started
