---

- name: Checking whether BigFix agent installed
  win_service:
    name: besclient
  register: agent

- name: Remove a service
  win_service:
    name: besclient
    state: absent
  when: agent is defined and agent.exists
  ignore_errors: yes

- name: Create necessary folders
  win_file:
    path: '{{ item }}'
    recurse: yes
    state: directory
  with_items:
  - '{{ windows_agent_log_path }}'
  - '{{ windows_agent_install_path }}'
 
- name: Copy actionsite.afxm to {{ windows_bigfix_agent_path }} directory
  win_copy:
    src: bigfix_license.afxm
    dest: '{{ windows_agent_install_path }}\actionSite.afxm'

- name: Copy clientsettings.cfg to {{ windows_bigfix_agent_path }} directory
  win_template:
    src: besclient.config.j2
    dest: '{{ windows_agent_install_path }}\clientsettings.cfg'

- name: Copy BigFix installer
  win_copy:
    src: 'BigFixAgent.msi'
    dest: '{{ windows_agent_install_path }}\{{ BIGFIX_AGENT_PACKAGE_NAME }}'

- name: Install Bigfix agent
  win_package:
    path: '{{ windows_agent_install_path }}\{{ BIGFIX_AGENT_PACKAGE_NAME }}'
    log_path: '{{ windows_agent_log_path }}\bigfix_log.txt'
    state: present

- name: Verify Bigfix service has started
  win_service:
    name: besclient
    enabled: yes
    state: started
    start_mode: auto
  ignore_errors: yes

